app/models.py
from app import db

class Task(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    status = db.Column(db.String(20), nullable=False, default='Pending')
    

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()

def create_app():
    app = Flask(__name__)
    app.secret_key = "your_secret_key"
    app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///site.db"
    app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
    
    db.init_app(app)
    
    from app.routes.auth import auth_bp
    from app.routes.tasks import tasks_bp
    
    app.register_blueprint(auth_bp)
    app.register_blueprint(tasks_bp)

    return app

app/routes/auth.py
from flask import Blueprint, render_template, request
from flask import flash, url_for, redirect, session


auth_bp = Blueprint("auth", __name__)

USER_CREDENTIALS ={
    'username':'admin',
    'password':'12345'
}

@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == "POST":
        username = request.form.get('username')
        password = request.form.get('password')
        
        if username == USER_CREDENTIALS['username'] and password == USER_CREDENTIALS['password']:
            session['user'] = username
            flash('login successful', 'success')
        else:
            flash('login failed', 'danger')
            return redirect(url_for('auth.login'))
    return render_template('login.html')

@auth_bp.route('/logout')
def logout():
    session.pop('user', None)
    flash('logout successful', 'info')
    return redirect(url_for('auth.login'))

app/routes/tasks.py
from flask import Blueprint, render_template, request
from flask import flash, url_for, redirect, session

from app import db
from app.models import Task

tasks_bp = Blueprint("tasks", __name__)

@tasks_bp.route('/')
def view_task():
    if 'user' not in session:
        flash('Please log in to view tasks', 'warning')
        return redirect(url_for('auth.login'))
    tasks = Task.query.all()
    return render_template('tasks.html', tasks=tasks)

@tasks_bp.route('/add', methods=['POST'])
def add_task():
    if 'user' not in session:
        flash('Please log in to add tasks', 'danger')
        return redirect(url_for('auth.login'))
    title = request.form.get('title')
    if title:
        new_task = Task(title=title, status='pending')
        db.session.add(new_task)
        db.session.commit()
        flash('Task added successfully', 'success')
    return redirect(url_for('tasks.view_task'))

@tasks_bp.route('/toggle/<int:task_id>', methods=['POST'])
def toggle_task(task_id):
    if 'user' not in session:
        flash('Please log in to toggle tasks', 'danger')
        return redirect(url_for('auth.login'))
    task = Task.query.get_or_404(task_id)
    if task.status == "Pending":
        task.status = "Working"
    elif task.status == "Working":
        task.status = 'Done'
    else:
        task.status == "Pending"
    db.session.commit()
    return redirect(url_for('tasks.view_task'))

@tasks_bp.route('/clear/<int:task_id>', methods=['POST'])
def clear_task(task_id):
    if 'user' not in session:
        flash('Please log in to clear tasks', 'danger')
        return redirect(url_for('auth.login'))
    task = Task.query.get_or_404(task_id)
    db.session.delete(task)
    db.session.commit()
    flash('Task cleared successfully', 'success')
    return redirect(url_for('tasks.view_task', task_id = task.id))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}todo-app{% endblock %}</title>
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/style.css') }}"
    />
  </head>
  <body>
    <header>
      <div class="container">
        <h1>My Todo-App</h1>
        <nav>
          <a href="{{ url_for('tasks.view_task')}}">Home</a>
          {% if 'user' in session%}
          <a href="{{ url_for('auth.logout')}}">Logout</a>
          {% else %}
          <a href="{{url_for('auth.login')}}">Login</a>
          {% endif %}
        </nav>
      </div>
    </header>

    <main class="container">
      {% with messages = get_flashed_messages(with_categories=True) %} {% for
      category, message in messages %}
      <div class="flash {{ category }}">{{ message }}</div>
      {% endfor %} {%endwith%} {% block content %}{% endblock %}
    </main>
    <footer>
      <div class="container">
        <p>&copy; 2023 My Todo-App</p>
      </div>
    </footer>
  </body>
</html>

app/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
%}
<div class="login-box">
  <h2>Login</h2>
  <form method="POST">
    <div class="form-group">
      <label for="username">Username</label><br />
      <input type="text" name="username" id="username" required /><br />
    </div>

    <div class="form-group">
      <label for="password">Password</label><br />
      <input type="password" name="password" id="password" required /><br />
      <button type="submit" class="btn">Login</button>
    </div>
  </form>
</div>
{% endblock %}

app/templates/register.html
{% extends "base.html" %} {% block title %} - My Todo-App{% endblock %} {% block
content %}
<h1>Registration Comming soon.....</h1>
{%endblock%}

app/templates/tasks.html
{% extends "base.html" %} {% block title %}Task List{% endblock %} {% block
content %}
<div class="task-box">
  <h2>Your Task</h2>
  <form action="{{url_for("tasks.add_task")}}" method="POST" class="task-form">
    <input type="text" name="title" id="title" placeholder="Enter task title" required />
    <button type="submit">Add Task</button>

  </form>
  {% if tasks %}
  <form action="{{url_for('tasks.clear_task', task_id=task.id)}}" method='POST' class="clear-task-form">
    <button type="submit" class='btn-btn-clear'>Clear Tasks</button>
  </form>

  <table class="tasks-table">
    <thead>
        <tr>Task</tr>
        <tr>Status</tr>
        <tr>Change</tr>
    </thead>
    <tbody>
        {% for task in tasks %}
        <tr>
          <td>{{loop.index}}</td>
          <td>{{ task.title }}</td>
          <td>
            <span class="badge {{ task.status|lower }}">{{ task.status }}</span>
          </td>
          <td>
            <form action="{{url_for('tasks.toggle_task')}}" method='POST'>
              
              <button type="submit" class="btn-small">Next</button>
            </form>
          </td>
          
        </tr>
        {% endfor %}
    </tbody>
  </table>
  {% else %}
  <p>No tasks found.</p>
  {% endif %}
</div>
{% endblock%}